#COMBO_ENABLE =  yes
CONSOLE_ENABLE = yes
ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
LEADER_ENABLE = yes
LTO_ENABLE = yes
OLED_ENABLE = yes
WPM_ENABLE = yes
#QUANTUM_PAINTER_ENABLE = yes
#OLED_DRIVER_ENABLE = yes
CAPS_WORD_ENABLE = yes
#MIDI_ENABLE = no

RAW_ENABLE = no
VIA_ENABLE = no

AUDIO_ENABLE = no
BOOTMAGIC_ENABLE = no
COMMAND_ENABLE = no
GRAVE_ESC_ENABLE = no
KEY_LOCK_ENABLE = no
MAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
SPACE_CADET_ENABLE = no
STENO_ENABLE = no
TAP_DANCE_ENABLE = no
TERMINAL_ENABLE = no
UNICODE_ENABLE = no
VELOCIKEY_ENABLE = no

ifeq ($(strip $(ENCODER_ENABLE)), yes)
	SRC += encoder.c
endif
ifeq ($(strip $(OLED_ENABLE)), yes)
	SRC += oled.c
	SRC += keylogger.c
	#SRC += gfx/doge.c
endif
ifeq ($(strip $(RAW_ENABLE)), yes)
	SRC += hid.c
endif

